services:
  stats-server:
    build:
      context: ./stats_service/stats_server
      dockerfile: Dockerfile
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=stats-db
      - SPRING_DATASOURCE_PASSWORD=stats-db

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=stats-db
      - POSTGRES_USER=stats-db
      - POSTGRES_DB=stats-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build:
      context: ./ewm_service
      dockerfile: Dockerfile
    image: ewm-server
    container_name: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/ewm-db
      - SPRING_DATASOURCE_USERNAME=ewm-db
      - SPRING_DATASOURCE_PASSWORD=ewm-db

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=ewm-db
      - POSTGRES_USER=ewm-db
      - POSTGRES_DB=ewm-db
